name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Get version from Poetry
        id: get_version
        shell: bash
        run: |
          VERSION=$(poetry version -s)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with PyInstaller
        run: |
          poetry run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pg-budget-${{ runner.os }}-${{ env.VERSION }}
          path: dist/pg-budget*


  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: "pg-budget v${{ needs.build.outputs.version }}"
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
