name: CI

on:
  pull_request:
    branches: ["master"]

  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  ci:
    name: Lint & Type Check & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.9.2"
          host: linux
          
      - name: Install French locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen fr_FR.UTF-8

      - name: Install UV
        run: pip install uv

      - name: Run format
        run: uv run format

      - name: Run lint
        run: uv run lint

      - name: Run unit tests & coverage
        run: uv run test-cov
      
      - name: Run e2e tests 
        run: uv run test-e2e-fast
        env:
          QT_QPA_PLATFORM: offscreen